Vagrant.configure("2") do |config|
  config.vm.define "server1" do |server|
    server.vm.box = "generic/centos7"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "server1"
  end

  config.vm.define "server2" do |server|
    server.vm.box = "generic/centos7"
    server.vm.network "private_network", ip: "192.168.56.11"
    server.vm.hostname = "server2"
  end
end
